### ISSUE TITLE
Forge update?

### ISSUE THREAD

**Issue by logitechQ** [unilock/SortedEnchantments#1]
any plans to update the forge version?

**Comment by unilock** [comment]
There is a distinct possibility that the current Forge version will run on every Minecraft version including and above 1.18.2, but it's as of yet untested.

**Comment by logitechQ** [comment]
Interesting, I'll give it a test and report back on here

No dice
 Quick test confirms it does indeed not work

**Comment by unilock** [comment]
I've released a new version that should work on Forge 1.19 and above.

https://modrinth.com/mod/sorted-enchantments/version/1.0.0+1.19+forge
